workflows:
  scutum-test-task-workflow:
    name: Scutum Test Task Workflow
    environment:
      groups:
        - firebase
      flutter: stable
      vars:
        APP_ID: $APP_ID
        FIREBASE_TOKEN: $FIREBASE_TOKEN
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Check current location
        script: pwd
      - name: List contents of the current directory
        script: ls
      - name: Open scutum_test_task folder if it exists
        script: |
          if [ -d "scutum_test_task" ]; then
            cd scutum_test_task
            pwd
            ls
          else
            pwd
            ls
            echo "scutum_test_task directory does not exist."
          fi
      - name: Verify Flutter installation
        script: flutter --version
      - name: Install dependencies
        script: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          else
            echo "pubspec.yaml not found in the current directory."
            exit 1
          fi
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=APP_ID=$APP_ID --dart-define=FIREBASE_TOKEN=$FIREBASE_TOKEN
      - name: Build AAB
        script: |
          flutter build appbundle --release --dart-define=APP_ID=$APP_ID --dart-define=FIREBASE_TOKEN=$FIREBASE_TOKEN
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_KEY
        #firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $APP_ID
          groups: 
            - android_testers
          artifact_type: 'apk'
          #groups: 
          #    - android_testers
          #    artifact_type: 'aab'
          #    artifact_path: 'build/app/outputs/bundle/release/app-release.aab'
        
