workflows:
  generate_apk_workflow:
    name: Generate APK Workflow
    environment:
      android_signing:
        - keystore_reference
      groups:
        - firebase
      flutter: stable
      vars:
        APP_ID: $APP_ID # API KEY OF OpenWeatherMap API
        ANDROID_APP_ID: $ANDROID_APP_ID # Android App id
        FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT # Firebase service account json
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS # Path to Fireabse service account json file
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Check current location
        script: pwd
      - name: List contents of the current directory
        script: ls
      - name: Open scutum_test_task folder if it exists
        script: |
          if [ -d "scutum_test_task" ]; then
            cd scutum_test_task && pwd && ls
          else
            pwd
            ls
            echo "scutum_test_task directory does not exist."
          fi
      - name: Verify Flutter installation
        script: flutter --version
      - name: Install dependencies
        script: |
          cd scutum_test_task && pwd && ls
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          else
            pwd
            ls
            echo "pubspec.yaml not found in the current directory."
            exit 1
          fi
      - name: Run code generation
        script: |
         cd scutum_test_task && pwd && ls && flutter clean && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          cd scutum_test_task && pwd && ls && flutter build apk --release --dart-define=APP_ID=$APP_ID --no-tree-shake-icons
      - name: Check if APK exist
        script: |
          if [ -f "scutum_test_task/build/app/outputs/flutter-apk/app-release.apk" ]; then
            ls
            echo "APK file exists."
          else
            echo "APK file does not exist."
            exit 1
          fi
    artifacts:
      - scutum_test_task/build/**/outputs/**/*.apk
    publishing:
      firebase:
          firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
          android:
            app_id: $ANDROID_APP_ID
            groups: 
              - android_testers
            artifact_type: 'apk'