workflows:
  scutum-test-task-workflow:
    name: Scutum Test Task Workflow
    environment:
      groups:
        - firebase
      flutter: stable
      vars:
        APP_ID: $APP_ID
        FIREBASE_TOKEN: $FIREBASE_TOKEN
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Change to project directory
        script: cd scutum_test_task
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=APP_ID=$APP_ID --dart-define=FIREBASE_TOKEN=$FIREBASE_TOKEN
      - name: Build AAB
        script: |
          flutter build appbundle --release --dart-define=APP_ID=$APP_ID --dart-define=FIREBASE_TOKEN=$FIREBASE_TOKEN
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_KEY
        #firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $APP_ID
          groups: 
            - android_testers
            artifact_type: 'apk'
            artifact_path: 'build/app/outputs/flutter-apk/app-release.apk'
          #groups: 
          #    - android_testers
          #    artifact_type: 'aab'
          #    artifact_path: 'build/app/outputs/bundle/release/app-release.aab'
        
