workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......f
        # .......  
    ios-workflow-id:
        name: iOS Sample Workflow
        # ......