name: scutum_test_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3

  # Networn
  dio: ^5.4.1

  # Images
  cached_network_image: ^3.3.1

  # Navigation
  go_router: ^13.2.0

  # DI
  get_it: ^7.6.7
  
  # Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Other
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env/app_keys.json
