// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuduUHBMj5ngACG1MwvUG0Icx1BXButU',
    appId: '1:831846502146:web:b60c7b7e9373022d1bfc1b',
    messagingSenderId: '831846502146',
    projectId: 'scutum-test-task',
    authDomain: 'scutum-test-task.firebaseapp.com',
    storageBucket: 'scutum-test-task.appspot.com',
    measurementId: 'G-JZ80QELBDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymFys1vobP_IBJsNa-x_oB8YLwC7a_4w',
    appId: '1:831846502146:android:32d3685d4feec7c01bfc1b',
    messagingSenderId: '831846502146',
    projectId: 'scutum-test-task',
    storageBucket: 'scutum-test-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwszWDz7EBmuhhOtet9Z35ueTgQV1Ejg8',
    appId: '1:831846502146:ios:84bb6c8478e4b9461bfc1b',
    messagingSenderId: '831846502146',
    projectId: 'scutum-test-task',
    storageBucket: 'scutum-test-task.appspot.com',
    iosBundleId: 'com.example.scutumTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwszWDz7EBmuhhOtet9Z35ueTgQV1Ejg8',
    appId: '1:831846502146:ios:7ebd13e921092f8f1bfc1b',
    messagingSenderId: '831846502146',
    projectId: 'scutum-test-task',
    storageBucket: 'scutum-test-task.appspot.com',
    iosBundleId: 'com.example.scutumTestTask.RunnerTests',
  );
}
